version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gentest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gentest_db
      POSTGRES_USER: gentest_user
      POSTGRES_PASSWORD: gentest_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - gentest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gentest_user -d gentest_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Uncomment this if you want to include pgAdmin for database management
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: gentest-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gentest.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   networks:
  #     - gentest-network
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
    driver: local
  # pgadmin_data:
  #   driver: local

networks:
  gentest-network:
    driver: bridge